//! `tool-hello` — a tool extension.
//!
//! Generated by `make ext-new NAME=tool-hello KIND=tool`. Replace the stubs below;
//! they return real values rather than `todo!()` so this compiles from the
//! first build.
//!
//! Component-Model glue only, so it compiles for `wasm32` only.

#[cfg(target_arch = "wasm32")]
mod component {
    #[allow(
        unsafe_code,
        missing_docs,
        clippy::all,
        clippy::pedantic,
        clippy::nursery
    )]
    mod bindings {
        wit_bindgen::generate!({
            world: "tool-world",
            path: "../../../wit",
        });
    }

    use bindings::exports::jan_klod::interfaces::extension_lifecycle::{
        ExtensionContext, Guest as Lifecycle, HealthStatus,
    };
    // Named, not a glob. `clippy::wildcard-imports` is denied workspace-wide,
    // so a `::*` here would make the generated crate fail the repository's own
    // lints before its author had written a line — and the trait is aliased
    // because wit-bindgen calls every exported interface's trait `Guest`,
    // including the lifecycle one above.
    use bindings::exports::jan_klod::interfaces::tool_callable::{
        Guest as ToolCallable, ToolError, ToolMeta,
    };
    use bindings::jan_klod::interfaces::host_log::{self, LogLevel};

    fn log(level: LogLevel, message: &str) {
        host_log::log(level, "tool-hello", message, &[]);
    }

    struct Component;

    impl Lifecycle for Component {
        fn init(ctx: ExtensionContext) -> Result<(), String> {
            log(
                LogLevel::Info,
                &format!("init id={} version={}", ctx.id, ctx.version),
            );
            Ok(())
        }
        fn start() -> Result<(), String> {
            Ok(())
        }
        fn stop() {}
        fn health() -> HealthStatus {
            HealthStatus::Up
        }
    }

    impl ToolCallable for Component {
        fn meta() -> ToolMeta {
            ToolMeta {
                name: "tool-hello".to_string(),
                description: "Describe what this tool does — the model reads this.".to_string(),
                // JSON Schema for `invoke`'s argument string.
                arguments_schema: r#"{"type":"object","properties":{}}"#.to_string(),
            }
        }

        fn invoke(_arguments: String) -> Result<String, ToolError> {
            Ok("replace me".to_string())
        }
    }

    #[allow(
        unsafe_code,
        missing_docs,
        clippy::all,
        clippy::pedantic,
        clippy::nursery
    )]
    mod glue {
        use super::{bindings, Component};
        bindings::export!(Component with_types_in bindings);
    }
}
