// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package spike represents the world "jan-klod:spike/spike@0.1.0".
//
// Throwaway gate world for Slice 1a (go/no-go). Proves the Rust + Wasmtime
// host can load a TinyGo-built component and call an exported function across
// the Component Model boundary. Kept out of the canonical
// `jan-klod:interfaces` package on purpose — delete this directory together
// with `src/extensions/spike/` once the gate verdict is recorded.
package spike
