"""`tool-hello-py` — the Python twin of `tool-hello`.

The same tool, in a third language, against the same `wit/`. `tool-hello-ts`
proved a second language reaches the contracts; this one exists because the
two non-Rust toolchains fail differently, and the difference is the finding.

## What is different from the Rust twin, and what is not

Not different: the world, the interfaces, the host's treatment of it. The host
loads this the way it loads any component — no special case.

Different: **size**, and **what the runtime imports**. `componentize-py`
embeds CPython, so this component is ~18.4 MB against `tool-hello`'s 55 KB —
larger even than the TypeScript guest's 12.7 MB. And CPython's standard
library needs `wasi:filesystem`, `wasi:sockets` and `wasi:cli` to initialise,
so the component imports them. `docs/concepts/security-model.md` and #211
cover why that is inert and why it is still worth naming.

## Bindings, unlike the TypeScript path

`componentize-py bindings` generates a `wit_world` package from the WIT, and
the classes below implement its `Protocol`s. That is closer to `wit-bindgen`
than to `jco`: the shapes are checked when this module is componentized
against the generated package, not hand-matched. The generated package is
build output — it is regenerated by `make -C src/extensions py-guest` and not
committed, for the same reason `ext/` is not.
"""

import json

import wit_world
from wit_world.exports import ExtensionLifecycle as ExtensionLifecycleProtocol
from wit_world.exports import ToolCallable as ToolCallableProtocol
from wit_world.exports.extension_lifecycle import ExtensionContext, HealthStatus
from wit_world.exports.tool_callable import ToolMeta


class WitWorld(wit_world.WitWorld):
    """The world itself exports nothing beyond its interfaces."""


class ExtensionLifecycle(ExtensionLifecycleProtocol):
    def init(self, ctx: ExtensionContext) -> None:
        pass

    def start(self) -> None:
        pass

    def stop(self) -> None:
        pass

    def health(self) -> HealthStatus:
        return HealthStatus.UP


class ToolCallable(ToolCallableProtocol):
    def meta(self) -> ToolMeta:
        return ToolMeta(
            name="hello-py",
            description="Returns a greeting. The Python twin of tool-hello.",
            arguments_schema=json.dumps(
                {"type": "object", "properties": {"name": {"type": "string"}}}
            ),
        )

    def invoke(self, arguments: str) -> str:
        """`arguments` is a JSON string and the result is a JSON string — the
        interface says so, and a tool that returned bare prose would be
        readable to a person and not to the loop.
        """
        who = "world"
        try:
            parsed = json.loads(arguments or "{}")
        except ValueError:
            # A malformed argument object is the caller's, and greeting the
            # world is a better answer than a trap the loop reports as a tool
            # crash.
            parsed = {}
        if isinstance(parsed, dict) and isinstance(parsed.get("name"), str):
            who = parsed["name"] or "world"
        return json.dumps({"greeting": f"hello, {who}, from Python"})
