#!/bin/sh
# Generate a new extension crate, registered and ready to build.
#
# Usage: scripts/ext-new.sh <name> <kind>
#   kind ∈ provider | tool | interceptor | registry-skills | registry-mcp
#
# Writes src/extensions/<name>/, then registers the crate in the extensions
# workspace and in the Makefile's GUESTS — so `make extensions` picks it up with
# no second manual step, and `scripts/manifests.sh` generates its manifest from
# its real imports.
#
# ## Why shell rather than an xtask
#
# What differs between kinds is one `world:` line and one trait impl. A Rust
# xtask would need its own crate, its own build and its own place in the
# workspace to do string substitution that `sed` already does — and it would be
# the only build tool here that is not a Makefile target calling a script. If
# the per-kind table ever grows logic rather than text, revisit.
#
# ## Why the stubs compile
#
# A template whose first build fails teaches the wrong thing first. Every stub
# returns a real value rather than `todo!()`: an author deletes a body and writes
# theirs, instead of chasing a panic through a toolchain they have not learned
# yet.
set -eu

NAME="${1:-}"
KIND="${2:-}"
# The language axis (#187). Rust unless asked otherwise, because every
# first-party extension is Rust and a default that surprises is worse than a
# flag nobody passes.
LANG="${3:-rust}"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
# Overridable so the self-test can generate into a scratch directory and
# compare, rather than writing into the workspace to check what it writes.
EXT="${EXT_ROOT:-$ROOT/src/extensions}"

usage() {
    echo "usage: ext-new.sh <name> <kind> [lang]" >&2
    echo "  kind ∈ provider | tool | interceptor | registry-skills | registry-mcp" >&2
    echo "  lang ∈ rust (default) | ts" >&2
    exit 2
}

[ -n "$NAME" ] && [ -n "$KIND" ] || usage
case "$NAME" in
    *[!a-z0-9-]* | "" | -* ) echo "ext-new: name must be lowercase letters, digits and dashes: $NAME" >&2; exit 2 ;;
esac
[ -e "$EXT/$NAME" ] && { echo "ext-new: $EXT/$NAME already exists" >&2; exit 2; }

# The world each kind binds, the interface it exports beside
# extension-lifecycle, and the types that interface's stub names. This table
# *is* the difference between kinds; everything below it is identical for all
# five.
case "$KIND" in
    provider)
        WORLD="provider-world";       IFACE="llm_provider";   TRAIT="LlmProvider"
        TYPES="CompletionChunk, CompletionRequest, ProviderError, ProviderInfo, StreamHandle" ;;
    tool)
        WORLD="tool-world";           IFACE="tool_callable";  TRAIT="ToolCallable"
        TYPES="ToolError, ToolMeta" ;;
    interceptor)
        WORLD="interceptor-world";    IFACE="interceptor";    TRAIT="Interceptor"
        TYPES="Decision, InterceptInput, InterceptorError, Phase" ;;
    registry-skills)
        WORLD="skill-registry-world"; IFACE="skill_registry"; TRAIT="SkillRegistry"
        TYPES="SkillError, SkillInfo" ;;
    registry-mcp)
        WORLD="mcp-registry-world";   IFACE="mcp_registry";   TRAIT="McpRegistry"
        TYPES="McpError, ServerInfo, ToolInfo" ;;
    *) echo "ext-new: unknown kind: $KIND" >&2; usage ;;
esac


# --- TypeScript ---------------------------------------------------------------
#
# A second language, generated the same way. What differs from the Rust path is
# everything mechanical and nothing structural: no Cargo.toml, no generated
# bindings to import, and registration in `TS_GUESTS` rather than `GUESTS`.
#
# `jco` lowers WIT's kebab-case to lowerCamelCase, so an interface becomes an
# export name and a record field becomes a property. There is nothing to
# generate bindings *from* — the component is built from this module against
# `wit/`, and the componentize step is what checks the shapes below match.
#
# Only the kinds a third party is likely to write by hand. A provider or a
# registry in JavaScript is possible and nobody has wanted one; adding a stub
# for a kind nobody writes is a template to keep correct for free.
if [ "$LANG" = "ts" ]; then
    case "$KIND" in
        tool|interceptor) ;;
        *)
            echo "ext-new: LANG=ts has no template for kind '$KIND'" >&2
            echo "  supported: tool | interceptor — add a stub to ext-new.sh for others" >&2
            exit 2 ;;
    esac

    mkdir -p "$EXT/$NAME/src"

    cat > "$EXT/$NAME/package.json" <<EOF
{
  "name": "$NAME",
  "version": "0.1.0",
  "private": true,
  "description": "A $KIND extension in TypeScript. Replace this description with what it does.",
  "type": "module"
}
EOF

    cat > "$EXT/$NAME/src/guest.ts" <<EOF
/**
 * \`$NAME\` — a $KIND extension in TypeScript.
 *
 * Generated by \`make ext-new NAME=$NAME KIND=$KIND LANG=ts\`. Replace the stubs
 * below; they return real values rather than throwing, so this componentizes
 * and runs from the first build.
 *
 * Built by \`make -C src/extensions ts-guest\`, which needs \`jco\` on PATH and
 * skips where it is absent. The component carries a JavaScript engine, so it
 * is ~12.7 MB against a Rust guest's ~55 KB — the price of the language, not
 * of this extension.
 */

/** The world's \`extension-lifecycle\` export. */
export const extensionLifecycle = {
  init(_context: { id: string; version: string }): void {},
  start(): void {},
  stop(): void {},
  /** \`health-status\` is an enum; jco lowers its cases to strings. */
  health(): string {
    return "up";
  },
};
EOF

    # The kind-specific export is appended rather than captured in a variable:
    # a heredoc inside `$( )` is scanned for quotes by the shell before the
    # heredoc's own quoting applies, so a single apostrophe in a doc comment
    # ("the world's export") makes the whole script unparseable. Appending
    # keeps the prose free.
    if [ "$KIND" = "tool" ]; then
        cat >> "$EXT/$NAME/src/guest.ts" <<'EOF'

/** The world's `tool-callable` export. */
export const toolCallable = {
  meta() {
    return {
      name: "NAME_PLACEHOLDER",
      description: "Describe what this tool does — the model reads this.",
      // JSON Schema for `invoke`'s argument string.
      argumentsSchema: JSON.stringify({ type: "object", properties: {} }),
    };
  },

  /** `arguments` is a JSON string and so is the result; the interface says so. */
  invoke(_args: string): string {
    return "replace me";
  },
};
EOF
    else
        cat >> "$EXT/$NAME/src/guest.ts" <<'EOF'

/** The world's `interceptor` export. */
export const interceptor = {
  /**
   * `proceed` changes nothing, which is the right default: an interceptor that
   * has not decided anything must not alter the turn.
   */
  intercept(_input: unknown): { tag: string } {
    return { tag: "proceed" };
  },

  /**
   * Nothing yet. Subscribe only to the phases you act on — the host calls you
   * for every one you name.
   */
  subscribedPhases(): string[] {
    return [];
  },
};
EOF
    fi

    # The stubs are quoted heredocs, so the name is substituted after the
    # write. In-place editing is not portable; write beside and move.
    sed "s/NAME_PLACEHOLDER/$NAME/g" "$EXT/$NAME/src/guest.ts" > "$EXT/$NAME/src/guest.ts.tmp" \
        && mv "$EXT/$NAME/src/guest.ts.tmp" "$EXT/$NAME/src/guest.ts"

    # Registration: the TypeScript list, not the cargo one. Idempotent for the
    # same reason the Rust path is.
    if [ -f "$EXT/Makefile" ] && ! grep -q "TS_GUESTS :=.*[ =]$NAME\( \|$\)" "$EXT/Makefile"; then
        awk -v name="$NAME" '
            /^TS_GUESTS :=/ && !done { print $0 " " name; done = 1; next }
            { print }
        ' "$EXT/Makefile" > "$EXT/Makefile.tmp" && mv "$EXT/Makefile.tmp" "$EXT/Makefile"
    fi

    echo "ext-new: wrote $EXT/$NAME ($KIND, $WORLD, TypeScript)"
    echo "ext-new: registered in TS_GUESTS"
    echo "ext-new: next — \`make -C src/extensions ts-guest\` builds it (needs jco)"
    exit 0
fi

mkdir -p "$EXT/$NAME/src"

cat > "$EXT/$NAME/Cargo.toml" <<EOF
[package]
name = "$NAME"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish.workspace = true
description = "A $KIND extension. Replace this description with what it does."

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen.workspace = true

[lints]
workspace = true
EOF

# --- the exported interface's stub body, per kind ----------------------------
stub_tool() {
    cat <<'EOF'
    impl ToolCallable for Component {
        fn meta() -> ToolMeta {
            ToolMeta {
                name: "NAME_PLACEHOLDER".to_string(),
                description: "Describe what this tool does — the model reads this.".to_string(),
                // JSON Schema for `invoke`'s argument string.
                arguments_schema: r#"{"type":"object","properties":{}}"#.to_string(),
            }
        }

        fn invoke(_arguments: String) -> Result<String, ToolError> {
            Ok("replace me".to_string())
        }
    }
EOF
}

stub_provider() {
    cat <<'EOF'
    impl LlmProvider for Component {
        fn complete(_request: CompletionRequest) -> Result<StreamHandle, ProviderError> {
            Err(ProviderError::Unreachable)
        }

        fn next_chunk(_handle: StreamHandle) -> Option<CompletionChunk> {
            None
        }

        fn close_stream(_handle: StreamHandle) {}

        fn info() -> ProviderInfo {
            ProviderInfo {
                id: "NAME_PLACEHOLDER".to_string(),
                supported_models: Vec::new(),
            }
        }
    }
EOF
}

stub_interceptor() {
    cat <<'EOF'
    impl Interceptor for Component {
        fn intercept(_input: InterceptInput) -> Result<Decision, InterceptorError> {
            // `Proceed` changes nothing, which is the right default: an
            // interceptor that has not decided anything must not alter the turn.
            Ok(Decision::Proceed)
        }

        fn subscribed_phases() -> Vec<Phase> {
            // Nothing yet. Subscribe only to the phases you act on — the host
            // calls you for every one you name.
            Vec::new()
        }
    }
EOF
}

stub_registry_skills() {
    cat <<'EOF'
    impl SkillRegistry for Component {
        fn list_skills() -> Result<Vec<SkillInfo>, SkillError> {
            Ok(Vec::new())
        }

        fn get_skill(_name: String) -> Result<SkillInfo, SkillError> {
            Err(SkillError::NotFound)
        }

        fn invoke(_name: String, _arguments: String) -> Result<String, SkillError> {
            Err(SkillError::NotFound)
        }

        fn reload() -> Result<(), SkillError> {
            Ok(())
        }
    }
EOF
}

stub_registry_mcp() {
    cat <<'EOF'
    impl McpRegistry for Component {
        fn list_servers() -> Result<Vec<ServerInfo>, McpError> {
            Ok(Vec::new())
        }

        fn list_tools() -> Result<Vec<ToolInfo>, McpError> {
            Ok(Vec::new())
        }

        fn invoke_tool(_name: String, _arguments: String) -> Result<String, McpError> {
            Err(McpError::ToolNotFound)
        }

        fn reconnect(_server_id: String) -> Result<(), McpError> {
            Err(McpError::ServerNotFound)
        }
    }
EOF
}

case "$KIND" in
    provider)        STUB="$(stub_provider)" ;;
    tool)            STUB="$(stub_tool)" ;;
    interceptor)     STUB="$(stub_interceptor)" ;;
    registry-skills) STUB="$(stub_registry_skills)" ;;
    registry-mcp)    STUB="$(stub_registry_mcp)" ;;
esac
STUB="$(printf '%s' "$STUB" | sed "s/NAME_PLACEHOLDER/$NAME/g")"

cat > "$EXT/$NAME/src/lib.rs" <<EOF
//! \`$NAME\` — a $KIND extension.
//!
//! Generated by \`make ext-new NAME=$NAME KIND=$KIND\`. Replace the stubs below;
//! they return real values rather than \`todo!()\` so this compiles from the
//! first build.
//!
//! Component-Model glue only, so it compiles for \`wasm32\` only.

#[cfg(target_arch = "wasm32")]
mod component {
    #[allow(
        unsafe_code,
        missing_docs,
        clippy::all,
        clippy::pedantic,
        clippy::nursery
    )]
    mod bindings {
        wit_bindgen::generate!({
            world: "$WORLD",
            path: "../../../wit",
        });
    }

    use bindings::exports::jan_klod::interfaces::extension_lifecycle::{
        ExtensionContext, Guest as Lifecycle, HealthStatus,
    };
    // Named, not a glob. \`clippy::wildcard-imports\` is denied workspace-wide,
    // so a \`::*\` here would make the generated crate fail the repository's own
    // lints before its author had written a line — and the trait is aliased
    // because wit-bindgen calls every exported interface's trait \`Guest\`,
    // including the lifecycle one above.
    use bindings::exports::jan_klod::interfaces::$IFACE::{Guest as $TRAIT, $TYPES};
    use bindings::jan_klod::interfaces::host_log::{self, LogLevel};

    fn log(level: LogLevel, message: &str) {
        host_log::log(level, "$NAME", message, &[]);
    }

    struct Component;

    impl Lifecycle for Component {
        fn init(ctx: ExtensionContext) -> Result<(), String> {
            log(
                LogLevel::Info,
                &format!("init id={} version={}", ctx.id, ctx.version),
            );
            Ok(())
        }
        fn start() -> Result<(), String> {
            Ok(())
        }
        fn stop() {}
        fn health() -> HealthStatus {
            HealthStatus::Up
        }
    }

$STUB

    #[allow(
        unsafe_code,
        missing_docs,
        clippy::all,
        clippy::pedantic,
        clippy::nursery
    )]
    mod glue {
        use super::{bindings, Component};
        bindings::export!(Component with_types_in bindings);
    }
}
EOF

# --- registration ------------------------------------------------------------
#
# Both lists are flat text. Idempotent: re-registering an existing name would
# build it twice and `manifests.sh` would stage it twice, so each edit checks
# first.
# Registration is skipped where there is no workspace to register into — which
# is how the self-test generates into a scratch directory without needing to
# fabricate one.
if [ -f "$EXT/Cargo.toml" ] && ! grep -q "^    \"$NAME\"," "$EXT/Cargo.toml"; then
    # After the last existing member, so the list stays where it was.
    awk -v name="$NAME" '
        /^]/ && !done { print "    \"" name "\","; done = 1 }
        { print }
    ' "$EXT/Cargo.toml" > "$EXT/Cargo.toml.tmp" && mv "$EXT/Cargo.toml.tmp" "$EXT/Cargo.toml"
fi

if [ -f "$EXT/Makefile" ] && ! grep -q "GUESTS :=.*[ =]$NAME\( \|$\)" "$EXT/Makefile"; then
    awk -v name="$NAME" '
        /^GUESTS :=/ && !done { print $0 " " name; done = 1; next }
        { print }
    ' "$EXT/Makefile" > "$EXT/Makefile.tmp" && mv "$EXT/Makefile.tmp" "$EXT/Makefile"
fi

# Format what was just written, rather than hoping the template happens to be
# canonical. Acceptance line 2 of #111 asks that a generated crate pass
# `fmt --check` **untouched**, and the import line's length depends on how many
# types a kind names — so no single hand-written layout satisfies every kind.
# Formatting here makes that guarantee hold for kinds nobody has added yet.
#
# After registration, because `-p` needs the crate to be a workspace member.
if [ -f "$EXT/Cargo.toml" ]; then
    cargo fmt --manifest-path "$EXT/Cargo.toml" -p "$NAME"
else
    # No workspace: format the file directly, so a scratch generation is
    # byte-comparable with a registered one.
    rustfmt --edition 2021 "$EXT/$NAME/src/lib.rs"
fi

echo "ext-new: wrote $EXT/$NAME ($KIND, $WORLD)"
echo "ext-new: registered in the extensions workspace and GUESTS"
echo "ext-new: next — \`make extensions\` builds it and generates its manifest"
