#!/usr/bin/env sh
# Generate ext/<name>.manifest.toml for each staged guest component.
#
# A manifest declares what a component needs, so a registry can say "asks for
# network" before download and the host can refuse a component whose
# declaration and reality disagree (that refusal is a later slice; nothing
# reads these yet).
#
# `capabilities` is read from the component itself rather than from anything a
# guest author writes, which is the point: a declaration derived from the
# artifact cannot drift from it. Three traps in that reading, all easy to get
# wrong and all silent:
#
#   * The WIT output lists a world's *exports* too — `extension-lifecycle` and
#     `tool-callable` are what a guest implements, not what it needs. Only the
#     top-level `world root { … }` block's `import` lines count.
#   * Imports include type-only packages (`llm-types`, `store-types`). Those
#     are shapes; nothing is granted by importing one. Listing them would tell
#     an operator to grant `llm-types`, which means nothing and reads like
#     something. Only `host-*` interfaces are capabilities.
#   * **The reading is only as tight as the toolchain that produced the
#     imports.** `wit-bindgen` emits an import for what a guest's code uses,
#     so a Rust manifest is a statement of need. ComponentizeJS emits one for
#     every interface in the world, so a JavaScript guest's manifest is its
#     *world* — the most it could ask for, not what it asks for. `tool-hello`
#     declares `host-log`; `tool-hello-ts` does the same work and declares all
#     five. Still true that neither can claim more than its artifact; not true
#     that both can be read as need (#210).
#
# Usage: manifests.sh <extensions-dir> <ext-out-dir> <wit-dir> <guest>...
set -eu

EXT_SRC="$1"
OUT="$2"
WIT="$3"
shift 3

# Sibling scripts are found relative to this one, not to the caller's cwd —
# every invocation here comes through an absolute path from a Makefile or the
# selftest, and both run from different directories.
HERE="$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)"

command -v wasm-tools >/dev/null 2>&1 || {
    echo "manifests.sh: wasm-tools is required (cargo install wasm-tools)" >&2
    exit 1
}
command -v jaq >/dev/null 2>&1 || {
    echo 'manifests.sh: jaq is required — run: make setup' >&2
    exit 1
}

# One `jan-klod:interfaces` version, or none: once two WIT files disagree there
# is no answer to "which is the api-version", so refuse rather than pick.
# `wit-version.sh` is that reader, and it is a separate script because the
# version is read from two places now — here, and the check that a `wit/` edit
# bumped it. Two copies of this parser would be two answers.
API_VERSION="$(sh "$HERE/wit-version.sh" "$WIT")" || exit 1

METADATA="$(cargo metadata --no-deps --format-version 1 \
    --manifest-path "$EXT_SRC/Cargo.toml")"

mkdir -p "$OUT"

for guest in "$@"; do
    wasm="$OUT/$guest.wasm"
    [ -f "$wasm" ] || {
        echo "manifests.sh: $wasm is not staged; run 'make extensions' first" >&2
        exit 1
    }

    version="$(printf '%s' "$METADATA" |
        jaq -r --arg n "$guest" '.packages[] | select(.name == $n) | .version')"
    description="$(printf '%s' "$METADATA" |
        jaq -r --arg n "$guest" '.packages[] | select(.name == $n) | .description // ""')"
    # A guest need not be a cargo package: a non-Rust one carries its own
    # manifest instead, and the name, version and description come from there.
    # Read rather than defaulted — a component whose manifest said "0.0.0"
    # because nobody could find its version is worse than no manifest.
    if [ -z "$version" ] && [ -f "$EXT_SRC/$guest/package.json" ]; then
        version="$(jaq -r '.version // ""' "$EXT_SRC/$guest/package.json")"
        description="$(jaq -r '.description // ""' "$EXT_SRC/$guest/package.json")"
    fi
    [ -n "$version" ] || {
        echo "manifests.sh: $guest is neither a package in $EXT_SRC/Cargo.toml" >&2
        echo "  nor a directory with a package.json carrying a version" >&2
        exit 1
    }

    # `provider-openai` -> provider. The category is already the naming rule the
    # component resolver uses (`ext/<category>-<type>.wasm`), so it is read from
    # the name rather than stated twice and allowed to disagree.
    kind="${guest%%-*}"

    # The world block only, then its imports, then the host capabilities.
    capabilities="$(wasm-tools component wit "$wasm" |
        awk '/^world root \{/,/^\}/' |
        sed -n 's|^  import jan-klod:interfaces/\(host-[a-z-]*\)@.*|\1|p' |
        sort -u)"

    {
        echo "# Generated by scripts/manifests.sh — do not edit."
        echo "# Regenerate with \`make -C src/extensions manifests\`."
        echo "#"
        echo "# capabilities are read from the component's own imports, so this"
        echo "# file cannot claim less or more than the artifact beside it does."
        echo "name = \"$guest\""
        echo "version = \"$version\""
        echo "api-version = \"$API_VERSION\""
        echo "kind = \"$kind\""
        # Escaped, because a description is prose and prose contains quotes.
        printf 'description = "%s"\n' \
            "$(printf '%s' "$description" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g')"
        if [ -z "$capabilities" ]; then
            # An empty list, not an absent key: "needs nothing" is a claim worth
            # making, and a missing key reads as "nobody filled this in".
            echo "capabilities = []"
        else
            echo "capabilities = ["
            printf '    "%s",\n' $capabilities
            echo "]"
        fi
    } >"$OUT/$guest.manifest.toml"
done

echo "staged $# manifest(s) in $OUT"
