#!/usr/bin/env sh
# Generate ext/<name>.manifest.toml for each staged guest component.
#
# A manifest declares what a component needs, so a registry can say "asks for
# network" before download and the host can refuse a component whose
# declaration and reality disagree (that refusal is a later slice; nothing
# reads these yet).
#
# `capabilities` is read from the component itself rather than from anything a
# guest author writes, which is the point: a declaration derived from the
# artifact cannot drift from it. Two traps in that reading, both easy to get
# wrong and both silent:
#
#   * The WIT output lists a world's *exports* too — `extension-lifecycle` and
#     `tool-callable` are what a guest implements, not what it needs. Only the
#     top-level `world root { … }` block's `import` lines count.
#   * Imports include type-only packages (`llm-types`, `store-types`). Those
#     are shapes; nothing is granted by importing one. Listing them would tell
#     an operator to grant `llm-types`, which means nothing and reads like
#     something. Only `host-*` interfaces are capabilities.
#
# Usage: manifests.sh <extensions-dir> <ext-out-dir> <wit-dir> <guest>...
set -eu

EXT_SRC="$1"
OUT="$2"
WIT="$3"
shift 3

command -v wasm-tools >/dev/null 2>&1 || {
    echo "manifests.sh: wasm-tools is required (cargo install wasm-tools)" >&2
    exit 1
}
command -v jq >/dev/null 2>&1 || {
    echo "manifests.sh: jq is required" >&2
    exit 1
}

# One `jan-klod:interfaces` version, or none: once two WIT files disagree there
# is no answer to "which is the api-version", so refuse rather than pick.
API_VERSION="$(sed -n 's/^package jan-klod:interfaces@\([^;]*\);.*/\1/p' "$WIT"/*.wit \
    | sort -u)"
case "$API_VERSION" in
    *"
"*)
        echo "manifests.sh: $WIT/*.wit declare more than one package version:" >&2
        echo "$API_VERSION" >&2
        exit 1
        ;;
    "")
        echo "manifests.sh: no 'package jan-klod:interfaces@…' found in $WIT" >&2
        exit 1
        ;;
esac

METADATA="$(cargo metadata --no-deps --format-version 1 \
    --manifest-path "$EXT_SRC/Cargo.toml")"

mkdir -p "$OUT"

for guest in "$@"; do
    wasm="$OUT/$guest.wasm"
    [ -f "$wasm" ] || {
        echo "manifests.sh: $wasm is not staged; run 'make extensions' first" >&2
        exit 1
    }

    version="$(printf '%s' "$METADATA" |
        jq -r --arg n "$guest" '.packages[] | select(.name == $n) | .version')"
    description="$(printf '%s' "$METADATA" |
        jq -r --arg n "$guest" '.packages[] | select(.name == $n) | .description // ""')"
    [ -n "$version" ] || {
        echo "manifests.sh: $guest is not a package in $EXT_SRC/Cargo.toml" >&2
        exit 1
    }

    # `provider-openai` -> provider. The category is already the naming rule the
    # component resolver uses (`ext/<category>-<type>.wasm`), so it is read from
    # the name rather than stated twice and allowed to disagree.
    kind="${guest%%-*}"

    # The world block only, then its imports, then the host capabilities.
    capabilities="$(wasm-tools component wit "$wasm" |
        awk '/^world root \{/,/^\}/' |
        sed -n 's|^  import jan-klod:interfaces/\(host-[a-z-]*\)@.*|\1|p' |
        sort -u)"

    {
        echo "# Generated by scripts/manifests.sh — do not edit."
        echo "# Regenerate with \`make -C src/extensions manifests\`."
        echo "#"
        echo "# capabilities are read from the component's own imports, so this"
        echo "# file cannot claim less or more than the artifact beside it does."
        echo "name = \"$guest\""
        echo "version = \"$version\""
        echo "api-version = \"$API_VERSION\""
        echo "kind = \"$kind\""
        # Escaped, because a description is prose and prose contains quotes.
        printf 'description = "%s"\n' \
            "$(printf '%s' "$description" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g')"
        if [ -z "$capabilities" ]; then
            # An empty list, not an absent key: "needs nothing" is a claim worth
            # making, and a missing key reads as "nobody filled this in".
            echo "capabilities = []"
        else
            echo "capabilities = ["
            printf '    "%s",\n' $capabilities
            echo "]"
        fi
    } >"$OUT/$guest.manifest.toml"
done

echo "staged $# manifest(s) in $OUT"
