#!/bin/sh
# Prepare the crate the principal boundary verification test compiles (#255).
#
# The principal boundary test compiles a **real component** — wit-bindgen, our
# `interceptor-world`, an exported interceptor — inside the test's offline build,
# where the network is denied. Two things have to be true before that build can
# succeed offline, and neither is something a test can arrange from inside:
#
#   1. a lock file, because resolution picks the newest compatible version
#      rather than a cached one, and offline resolution of a fresh crate fails
#      on the first version nobody fetched;
#   2. the crates themselves *fetched and extracted*, because extraction writes
#      under `CARGO_HOME`, which is outside the workspace the test allows
#      writes to.
#
# So this runs once, online, outside the test environment: it writes the crate,
# locks it, and builds it — the build is what extracts. Afterwards the test's
# own offline build needs nothing from the network.
#
# ## Why not `cargo vendor`
#
# Vendoring is what an air-gapped operator does: 34 MB, 47 crates, copied into
# the workspace. Measured here, a lock plus the shared cargo cache costs about
# **1 MB** of `.crate` files that every other build on the machine can use, and
# needs no `.cargo/config.toml` redirect. Reads are unrestricted inside the test
# and `CARGO_HOME` is already in the environment, so the cache is reachable
# without granting anything. On a machine where disk is the scarce resource,
# that is the cheaper of the two by a factor of thirty.
#
# The fixture's own `target/` is removed at the end: the offline test build makes
# its own, and 168 MB to keep a copy nothing reads is the wrong trade.
set -eu

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DIR="${1:-$ROOT/.fixtures/principal-boundary-guest}"
EXT_DIR="$ROOT/ext"

mkdir -p "$DIR/src" "$DIR/wit" "$EXT_DIR"
# The whole package, because `generate!` parses every file in the directory.
# No `deps/`: nothing in it references an external package.
cp "$ROOT"/wit/*.wit "$DIR/wit/"

cat > "$DIR/Cargo.toml" <<'MANIFEST'
# Generated by scripts/principal-boundary-fixture.sh — regenerate, do not edit.
[package]
name = "principal-boundary-guest"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = "0.46"

# Debug info is most of what a wasm guest build writes: 385 MB with it, 168 MB
# without, and nothing debugs this. Disk is the constraint, not build time.
[profile.dev]
debug = false
strip = "debuginfo"
incremental = false

[workspace]
MANIFEST

cat > "$DIR/src/lib.rs" <<'SOURCE'
// Generated by scripts/principal-boundary-fixture.sh — regenerate, do not edit.
//
// Stands in for what an agent writes: an interceptor component that verifies
// guests can read the optional principal field at the `before-loop` phase.
// Scenario (a): Reads the principal and logs it.
// Scenario (b): Does not read the principal (shows backwards compatibility).
#[allow(unsafe_code, missing_docs, clippy::all, clippy::pedantic, clippy::nursery)]
mod bindings {
    wit_bindgen::generate!({
        world: "interceptor-world",
        path: "wit",
    });
}

use bindings::exports::jan_klod::interfaces::extension_lifecycle::{
    ExtensionContext, Guest as Lifecycle, HealthStatus,
};
use bindings::exports::jan_klod::interfaces::interceptor::{
    Decision, Guest as Interceptor, InterceptInput, InterceptorError, Phase,
};
use bindings::jan_klod::interfaces::host_log::{self, LogLevel};

struct Component;

impl Lifecycle for Component {
    fn init(_ctx: ExtensionContext) -> Result<(), String> {
        Ok(())
    }
    fn start() -> Result<(), String> {
        Ok(())
    }
    fn stop() {}
    fn health() -> HealthStatus {
        HealthStatus::Up
    }
}

impl Interceptor for Component {
    fn intercept(input: InterceptInput) -> Result<Decision, InterceptorError> {
        // Only process the before-loop phase
        if input.phase != Phase::BeforeLoop {
            return Ok(Decision::Proceed);
        }

        // Extract the user-turn state from the hook-state
        if let bindings::exports::jan_klod::interfaces::interceptor::HookState::BeforeLoop(
            user_turn,
        ) = &input.state
        {
            // Scenario (a): Read the principal and log it
            if let Some(ref principal) = user_turn.principal {
                let msg = format!("Principal is '{}'", principal);
                host_log::log(LogLevel::Info, "principal-boundary-guest", &msg, &[]);
            } else {
                host_log::log(LogLevel::Info, "principal-boundary-guest", "Principal is None", &[]);
            }
        }

        Ok(Decision::Proceed)
    }

    fn subscribed_phases() -> Vec<Phase> {
        vec![Phase::BeforeLoop]
    }
}

#[allow(unsafe_code, missing_docs, clippy::all, clippy::pedantic, clippy::nursery)]
mod glue {
    use super::{bindings, Component};
    bindings::export!(Component with_types_in bindings);
}
SOURCE

cd "$DIR"
# Online, once: resolve and fetch. Writes Cargo.lock.
cargo fetch --target wasm32-wasip2
# Offline from here, and the build is what extracts the sources the test will
# read. Also the proof the fixture compiles at all — a fixture that only *looks*
# right would fail in the test, where the diagnosis is worse.
cargo build --offline --locked --target wasm32-wasip2
test -f target/wasm32-wasip2/debug/principal_boundary_guest.wasm || {
    echo "principal-boundary-fixture: the fixture did not build" >&2
    exit 1
}

# Copy the built binary to ext/ so the test can find it
cp target/wasm32-wasip2/debug/principal_boundary_guest.wasm "$EXT_DIR/principal-boundary-guest.wasm"

rm -rf target

echo "principal-boundary-fixture: ready in $DIR"
echo "  the principal boundary test uses this; nothing here is committed"
echo "  binary staged at $EXT_DIR/principal-boundary-guest.wasm"
