#!/bin/sh
# Prepare the crate the end-to-end self-extension test compiles (#221).
#
# The chain test compiles a **real component** — wit-bindgen, our `tool-world`,
# an exported tool — inside `self-extend`'s jail, where the network is denied.
# Two things have to be true before that build can succeed offline, and neither
# is something a test can arrange from inside the jail:
#
#   1. a lock file, because resolution picks the newest compatible version
#      rather than a cached one, and offline resolution of a fresh crate fails
#      on the first version nobody fetched;
#   2. the crates themselves *fetched and extracted*, because extraction writes
#      under `CARGO_HOME`, which is outside the workspace the jail allows
#      writes to.
#
# So this runs once, online, outside the jail: it writes the crate, locks it,
# and builds it — the build is what extracts. Afterwards the test's own jailed
# build needs nothing from the network.
#
# ## Why not `cargo vendor`
#
# Vendoring is what an air-gapped operator does and what #192 measured: 34 MB,
# 47 crates, copied into the workspace. Measured here, a lock plus the shared
# cargo cache costs about **1 MB** of `.crate` files that every other build on
# the machine can use, and needs no `.cargo/config.toml` redirect. Reads are
# unrestricted inside the jail and `CARGO_HOME` is already in `BASE_ENV`, so
# the cache is reachable without granting anything. On a machine where disk is
# the scarce resource, that is the cheaper of the two by a factor of thirty.
#
# The fixture's own `target/` is removed at the end: the jailed build makes its
# own inside the test's workspace, and 168 MB to keep a copy nothing reads is
# the wrong trade.
set -eu

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DIR="${1:-$ROOT/.fixtures/self-extend-guest}"

mkdir -p "$DIR/src" "$DIR/wit"
# The whole package, because `generate!` parses every file in the directory.
# No `deps/`: nothing in it references an external package.
cp "$ROOT"/wit/*.wit "$DIR/wit/"

cat > "$DIR/Cargo.toml" <<'MANIFEST'
# Generated by scripts/self-extend-fixture.sh — regenerate, do not edit.
[package]
name = "self-built"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = "0.46"

# Debug info is most of what a wasm guest build writes: 385 MB with it, 168 MB
# without, and nothing debugs this. Disk is the constraint, not build time.
[profile.dev]
debug = false
strip = "debuginfo"
incremental = false

[workspace]
MANIFEST

cat > "$DIR/src/lib.rs" <<'SOURCE'
// Generated by scripts/self-extend-fixture.sh — regenerate, do not edit.
//
// Stands in for what an agent writes: the smallest component that is a real
// tool. It imports nothing, so the manifest that has to accompany it declares
// nothing, which keeps the chain test about the *chain* rather than about
// capability declaration.
#[allow(unsafe_code, missing_docs, clippy::all, clippy::pedantic, clippy::nursery)]
mod bindings {
    wit_bindgen::generate!({
        world: "tool-world",
        path: "wit",
    });
}

use bindings::exports::jan_klod::interfaces::extension_lifecycle::{
    ExtensionContext, Guest as Lifecycle, HealthStatus,
};
use bindings::exports::jan_klod::interfaces::tool_callable::{
    Guest as ToolCallable, ToolError, ToolMeta,
};

struct Component;

impl Lifecycle for Component {
    fn init(_ctx: ExtensionContext) -> Result<(), String> {
        Ok(())
    }
    fn start() -> Result<(), String> {
        Ok(())
    }
    fn stop() {}
    fn health() -> HealthStatus {
        HealthStatus::Up
    }
}

impl ToolCallable for Component {
    fn meta() -> ToolMeta {
        ToolMeta {
            name: "self-built".to_string(),
            description: "Answers with a phrase only this component knows.".to_string(),
            arguments_schema: r#"{"type":"object","properties":{}}"#.to_string(),
        }
    }

    // The phrase is what the chain test asserts on: it can only reach the
    // model if this component was compiled, installed, adopted and called.
    fn invoke(_arguments: String) -> Result<String, ToolError> {
        Ok("compiled-in-session".to_string())
    }
}

#[allow(unsafe_code, missing_docs, clippy::all, clippy::pedantic, clippy::nursery)]
mod glue {
    use super::{bindings, Component};
    bindings::export!(Component with_types_in bindings);
}
SOURCE

cd "$DIR"
# Online, once: resolve and fetch. Writes Cargo.lock.
cargo fetch --target wasm32-wasip2
# Offline from here, and the build is what extracts the sources the jailed
# build will read. Also the proof the fixture compiles at all — a fixture that
# only *looks* right would fail inside the jail, where the diagnosis is worse.
cargo build --offline --locked --target wasm32-wasip2
test -f target/wasm32-wasip2/debug/self_built.wasm || {
    echo "self-extend-fixture: the fixture did not build" >&2
    exit 1
}
rm -rf target

echo "self-extend-fixture: ready in $DIR"
echo "  the chain test compiles this inside the jail; nothing here is committed"
