// Code generated by wit-bindgen-go. DO NOT EDIT.

package spike

// Exports represents the caller-defined exports from "jan-klod:spike/spike@0.1.0".
var Exports struct {
	// Complete represents the caller-defined, exported function "complete".
	//
	// Echo the prompt back. The host prints whatever this returns.
	//
	//	complete: func(prompt: string) -> string
	Complete func(prompt string) (result string)
}
