// Code generated by wit-bindgen-go. DO NOT EDIT.

package spike

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "jan-klod:spike@0.1.0".

//go:wasmexport complete
//export complete
func wasmexport_Complete(prompt0 *uint8, prompt1 uint32) (result *string) {
	prompt := cm.LiftString[string]((*uint8)(prompt0), (uint32)(prompt1))
	result_ := Exports.Complete(prompt)
	result = &result_
	return
}
